// AUTO-GENERATED by frida-test - do not edit
/// <reference types="frida-gum" />
import type { AgentMessage, RunSummary } from "frida-test/protocol.js";
import "./globals.js";
import "./matchers.js";
import { registry, runTests } from "./registry.js";

/// IMPORT TESTS SUITES ///

function emit(message: AgentMessage): void {
  send(message);
}

let running: Promise<RunSummary> | null = null;

rpc.exports = {
  runTests(verbose: boolean = false): Promise<RunSummary> {
    running ??= runTests(registry, emit, verbose).then((summary) => {
      emit({ type: "run-finished" });
      return summary;
    });
    return running;
  },
};

emit({ type: "agent-ready" });
